"""
solver.py — Single source of truth for all FEM analysis.

This module wraps the anastruct library and provides a clean interface
for building, solving, and extracting results from 2D structural models.

Neither app.py nor api.py may import anastruct directly — all FEM
interactions go through this module.

Units throughout:
    Forces:       kN
    Lengths:      m
    Moments:      kNm
    Distributed:  kN/m
    Modulus E:    GPa  (converted to kN/m² internally: 1 GPa = 1e6 kN/m²)
    Area A:       cm²  (converted to m² internally: 1 cm² = 1e-4 m²)
    Inertia Iz:   cm⁴  (converted to m⁴ internally: 1 cm⁴ = 1e-8 m⁴)
    Displacement: mm   (in results only)
"""

from __future__ import annotations

import copy
import math
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

import numpy as np
import yaml
from anastruct import SystemElements
from anastruct.basic import FEMException

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Conversion factors
GPA_TO_KN_M2 = 1e6        # 1 GPa = 1 000 000 kN/m²
CM2_TO_M2 = 1e-4           # 1 cm² = 0.0001 m²
CM4_TO_M4 = 1e-8           # 1 cm⁴ = 0.00000001 m⁴
M_TO_MM = 1000.0           # 1 m = 1000 mm

# Sanity check threshold — displacements beyond this indicate numerical instability
MAX_DISPLACEMENT_M = 1e6   # 1000 km — clearly nonsensical

# Valid enumerations
VALID_SUPPORT_TYPES = {
    "fixed", "pinned", "roller_x", "roller_y", "rotational",
    "spring_linear_x", "spring_linear_y", "spring_rotational",
}
# NOTE: "free" was removed — a node with no support entry is simply free.
VALID_LOAD_TYPES = {"point_force", "UDL", "point_moment", "settlement"}
VALID_DIRECTIONS = {"Fx", "Fy", "Mz"}
VALID_STRUCTURE_TYPES = {"beam", "truss", "frame", "custom"}

# YAML file header
YAML_HEADER = """\
# -----------------------------------------------
# 2D FEM Model File
# Generated by FEM App v1.0
# Units: kN, m, kNm, GPa, cm2, cm4
# Edit this file directly or load it in the app
# -----------------------------------------------

"""

# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class NodeDef:
    """A node in the structural model."""
    id: int
    x: float  # m
    y: float  # m


@dataclass
class MemberDef:
    """A member (element) connecting two nodes."""
    id: int
    start_node: int
    end_node: int
    section_id: int = 1             # references CrossSectionDef.id


@dataclass
class SupportDef:
    """A support condition at a node."""
    node_id: int
    type: str = "pinned"            # see VALID_SUPPORT_TYPES
    spring_stiffness: Optional[float] = None  # kN/m or kNm/rad


@dataclass
class LoadDef:
    """A load applied to a node or member."""
    id: int
    type: str                       # see VALID_LOAD_TYPES
    node_or_member_id: int
    direction: str = "Fy"           # "Fx", "Fy", or "Mz"
    magnitude: float = 0.0          # kN, kN/m, or kNm depending on type
    udl_start: Optional[float] = None  # m from start node (None = full span)
    udl_end: Optional[float] = None    # m from start node (None = full span)


@dataclass
class MaterialDef:
    """A material definition."""
    id: int
    name: str = "Steel S275"
    E_GPa: float = 210.0  # GPa


@dataclass
class CrossSectionDef:
    """A cross-section definition referencing a material."""
    id: int
    name: str = "Custom"
    A_cm2: float = 100.0    # cm²
    Iz_cm4: float = 10000.0  # cm⁴
    material_id: int = 1     # references MaterialDef.id


@dataclass
class HingeDef:
    """Moment release (hinge) at one or both ends of a member."""
    member_id: int
    start_release: bool = False  # True = free rotation at start node
    end_release: bool = False    # True = free rotation at end node


@dataclass
class ModelDefinition:
    """Complete structural model definition."""
    structure_type: str = "frame"
    name: str = ""
    description: str = ""
    nodes: list[NodeDef] = field(default_factory=list)
    members: list[MemberDef] = field(default_factory=list)
    materials: list[MaterialDef] = field(default_factory=list)
    cross_sections: list[CrossSectionDef] = field(default_factory=list)
    supports: list[SupportDef] = field(default_factory=list)
    loads: list[LoadDef] = field(default_factory=list)
    hinges: list[HingeDef] = field(default_factory=list)
    mesh_size: int = 50  # FE sub-elements per member for mesh discretisation


@dataclass
class ReactionResult:
    """Reaction forces at a support node."""
    node_id: int
    Rx_kN: float
    Ry_kN: float
    Mz_kNm: float


@dataclass
class MemberResult:
    """Summary results for a single member."""
    member_id: int
    N_max_kN: float
    V_max_kN: float
    M_max_kNm: float
    max_displacement_mm: float
    M_max_location_m: float
    V_max_location_m: float
    N_signed_kN: float = 0.0  # signed axial: positive=tension, negative=compression


@dataclass
class NodeDisplacement:
    """Displacement of a node after solving."""
    node_id: int
    dx_mm: float
    dy_mm: float
    rz_mrad: float  # milliradians


@dataclass
class SolveResult:
    """Complete solution output."""
    status: str = "ok"
    error: Optional[str] = None
    reactions: list[ReactionResult] = field(default_factory=list)
    member_results: list[MemberResult] = field(default_factory=list)
    nodes_displaced: list[NodeDisplacement] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_model(model: ModelDefinition) -> Optional[str]:
    """
    Validate a ModelDefinition for completeness and consistency.

    Returns None if valid, or a human-readable error string.
    """
    if not model.nodes:
        return "Model has no nodes defined."
    if not model.members:
        return "Model has no members defined."
    if not model.materials:
        return "Model has no materials defined."
    if not model.cross_sections:
        return "Model has no cross-sections defined."
    if not model.supports:
        return "Model has no supports defined."
    if not model.loads:
        return "Model has no loads defined."

    # Check for duplicate node IDs
    node_ids = [n.id for n in model.nodes]
    if len(node_ids) != len(set(node_ids)):
        dupes = [nid for nid in node_ids if node_ids.count(nid) > 1]
        return f"Duplicate node IDs found: {set(dupes)}"

    # Check for duplicate member IDs
    member_ids = [m.id for m in model.members]
    if len(member_ids) != len(set(member_ids)):
        dupes = [mid for mid in member_ids if member_ids.count(mid) > 1]
        return f"Duplicate member IDs found: {set(dupes)}"

    # Check for duplicate material IDs
    mat_ids = [mat.id for mat in model.materials]
    if len(mat_ids) != len(set(mat_ids)):
        dupes = [mid for mid in mat_ids if mat_ids.count(mid) > 1]
        return f"Duplicate material IDs found: {set(dupes)}"

    # Check for duplicate cross-section IDs
    sec_ids = [s.id for s in model.cross_sections]
    if len(sec_ids) != len(set(sec_ids)):
        dupes = [sid for sid in sec_ids if sec_ids.count(sid) > 1]
        return f"Duplicate cross-section IDs found: {set(dupes)}"

    # Validate material properties
    for mat in model.materials:
        if mat.E_GPa <= 0:
            return f"Material {mat.id} has invalid E_GPa={mat.E_GPa}. Must be positive."

    # Validate cross-section references and properties
    mat_id_set = set(mat_ids)
    for sec in model.cross_sections:
        if sec.material_id not in mat_id_set:
            return f"Cross-section {sec.id} references non-existent material {sec.material_id}."
        if sec.A_cm2 <= 0:
            return f"Cross-section {sec.id} has invalid A_cm2={sec.A_cm2}. Must be positive."
        if sec.Iz_cm4 <= 0:
            return f"Cross-section {sec.id} has invalid Iz_cm4={sec.Iz_cm4}. Must be positive."

    node_id_set = set(node_ids)
    sec_id_set = set(sec_ids)
    member_id_set = set(member_ids)

    # Check members reference valid nodes, sections, and are not zero-length
    for m in model.members:
        if m.start_node not in node_id_set:
            return f"Member {m.id} references non-existent start node {m.start_node}."
        if m.end_node not in node_id_set:
            return f"Member {m.id} references non-existent end node {m.end_node}."
        if m.start_node == m.end_node:
            return f"Member {m.id} has the same start and end node ({m.start_node}). Members must connect two different nodes."
        if m.section_id not in sec_id_set:
            return f"Member {m.id} references non-existent cross-section {m.section_id}."

    # Check duplicate node coordinates
    coords = [(n.x, n.y) for n in model.nodes]
    if len(coords) != len(set(coords)):
        for i, c1 in enumerate(coords):
            for j, c2 in enumerate(coords):
                if i < j and c1 == c2:
                    return (
                        f"Nodes {model.nodes[i].id} and {model.nodes[j].id} "
                        f"have the same coordinates ({c1[0]}, {c1[1]})."
                    )

    # Check supports reference valid nodes
    for s in model.supports:
        if s.node_id not in node_id_set:
            return f"Support references non-existent node {s.node_id}."
        if s.type not in VALID_SUPPORT_TYPES:
            return f"Support at node {s.node_id} has invalid type '{s.type}'."
        if s.type.startswith("spring") and s.spring_stiffness is None:
            return f"Spring support at node {s.node_id} requires a spring_stiffness value."

    # Check loads reference valid nodes/members
    for load in model.loads:
        if load.type not in VALID_LOAD_TYPES:
            return f"Load {load.id} has invalid type '{load.type}'."
        if load.type == "UDL":
            if load.node_or_member_id not in member_id_set:
                return f"UDL load {load.id} references non-existent member {load.node_or_member_id}."
            if load.direction not in ("Fx", "Fy"):
                return f"UDL load {load.id} has invalid direction '{load.direction}'. UDL supports Fx or Fy only."
        else:
            if load.node_or_member_id not in node_id_set:
                return f"Load {load.id} references non-existent node {load.node_or_member_id}."

    # Check hinges reference valid members
    hinged_members = set()
    for h in model.hinges:
        if h.member_id not in member_id_set:
            return f"Hinge references non-existent member {h.member_id}."
        if not h.start_release and not h.end_release:
            return f"Hinge on member {h.member_id} has no releases. At least one end must be released."
        if h.member_id in hinged_members:
            return f"Duplicate hinge definition for member {h.member_id}."
        hinged_members.add(h.member_id)

    # Check that supported nodes are connected to at least one member
    connected_nodes = set()
    for m in model.members:
        connected_nodes.add(m.start_node)
        connected_nodes.add(m.end_node)

    for s in model.supports:
        if s.node_id not in connected_nodes:
            return (
                f"Support at node {s.node_id} is not connected to any member. "
                f"All supported nodes must be part of the structure."
            )

    return None


# ---------------------------------------------------------------------------
# Build and solve
# ---------------------------------------------------------------------------


def _build_system(model: ModelDefinition) -> tuple[SystemElements, dict[int, int], dict[int, int]]:
    """
    Build an anastruct SystemElements from a ModelDefinition.

    Returns:
        ss: The SystemElements object (unsolved).
        node_id_map: Maps model node ID -> anastruct node ID.
        elem_id_map: Maps model member ID -> anastruct element ID.
    """
    # anastruct assigns its own sequential IDs, so we track the mapping
    ss = SystemElements(EA=1e6, EI=1e4, mesh=model.mesh_size)

    node_id_map: dict[int, int] = {}   # model node ID -> anastruct node ID
    elem_id_map: dict[int, int] = {}   # model member ID -> anastruct element ID

    # Build lookup maps
    node_coords = {n.id: (n.x, n.y) for n in model.nodes}
    mat_map = {m.id: m for m in model.materials}
    sec_map = {s.id: s for s in model.cross_sections}
    hinge_map = {h.member_id: h for h in model.hinges}

    # Add elements (this also creates nodes in anastruct)
    for member in model.members:
        x1, y1 = node_coords[member.start_node]
        x2, y2 = node_coords[member.end_node]

        # Resolve section -> material -> properties
        sec = sec_map[member.section_id]
        mat = mat_map[sec.material_id]
        EA = mat.E_GPa * GPA_TO_KN_M2 * sec.A_cm2 * CM2_TO_M2  # kN
        EI = mat.E_GPa * GPA_TO_KN_M2 * sec.Iz_cm4 * CM4_TO_M4  # kNm²

        # Build spring parameter for hinges (moment releases)
        spring = None
        if member.id in hinge_map:
            h = hinge_map[member.id]
            spring = {}
            if h.start_release:
                spring[1] = 0
            if h.end_release:
                spring[2] = 0

        elem_id = ss.add_element(
            location=[[x1, y1], [x2, y2]],
            EA=EA,
            EI=EI,
            spring=spring if spring else None,
        )

        elem_id_map[member.id] = elem_id

    # Map model node IDs to anastruct node IDs by coordinate lookup.
    # We cannot rely on element node_id1/node_id2 ordering because anastruct
    # may internally swap start/end nodes relative to the input coordinates.
    for model_node in model.nodes:
        an_nid = ss.find_node_id(vertex=[model_node.x, model_node.y])
        node_id_map[model_node.id] = an_nid

    # Add supports
    for support in model.supports:
        an_node = node_id_map[support.node_id]

        if support.type == "fixed":
            ss.add_support_fixed(node_id=an_node)
        elif support.type == "pinned":
            ss.add_support_hinged(node_id=an_node)
        elif support.type == "roller_x":
            # Free to slide in X, restrained in Y
            ss.add_support_roll(node_id=an_node, direction="x")
        elif support.type == "roller_y":
            # Free to slide in Y, restrained in X
            ss.add_support_roll(node_id=an_node, direction="y")
        elif support.type == "rotational":
            # Restrained rotation only, free to translate
            ss.add_support_rotational(node_id=an_node)
        elif support.type == "spring_linear_x":
            ss.add_support_spring(
                node_id=an_node, translation=1, k=support.spring_stiffness
            )
        elif support.type == "spring_linear_y":
            ss.add_support_spring(
                node_id=an_node, translation=2, k=support.spring_stiffness
            )
        elif support.type == "spring_rotational":
            ss.add_support_spring(
                node_id=an_node, translation=3, k=support.spring_stiffness
            )

    # Pre-process UDL loads: group by member to handle multiple UDLs on same member.
    # anastruct's q_load() overwrites previous calls on the same element, so we must
    # combine Fx and Fy UDLs into a single q_load call using the q_perp parameter.
    from collections import defaultdict
    udl_groups: dict[int, dict[str, float]] = defaultdict(lambda: {"Fx": 0.0, "Fy": 0.0})
    for load in model.loads:
        if load.type == "UDL":
            udl_groups[load.node_or_member_id][load.direction] += load.magnitude

    # Add loads
    applied_udl_members: set[int] = set()
    for load in model.loads:
        if load.type == "point_force":
            an_node = node_id_map[load.node_or_member_id]
            fx = load.magnitude if load.direction == "Fx" else 0.0
            fy = load.magnitude if load.direction == "Fy" else 0.0
            # anastruct with invert_y_loads=True: positive Fy = downward
            # Our convention: negative magnitude = downward force
            # So we negate Fy to match anastruct's inverted convention
            ss.point_load(node_id=an_node, Fx=fx, Fy=-fy)

        elif load.type == "UDL":
            member_id = load.node_or_member_id
            if member_id in applied_udl_members:
                continue  # Already applied combined UDL for this member
            applied_udl_members.add(member_id)

            an_elem = elem_id_map[member_id]
            total_qx = udl_groups[member_id]["Fx"]  # positive = rightward
            total_qy = udl_groups[member_id]["Fy"]   # our convention: negative = downward

            # Convert to anastruct convention:
            # direction="y" with invert_y_loads: positive q = downward
            # q_perp with direction="y": perpendicular to y = x-direction
            qy_an = -total_qy  # negate because anastruct inverts Y
            qx_an = total_qx   # x-direction, no inversion

            if total_qx != 0.0 and total_qy != 0.0:
                # Both directions present — use q_perp to apply in single call
                ss.q_load(q=qy_an, element_id=an_elem, direction="y", q_perp=qx_an)
            elif total_qy != 0.0:
                # Fy only
                ss.q_load(q=qy_an, element_id=an_elem, direction="y")
            elif total_qx != 0.0:
                # Fx only
                ss.q_load(q=qx_an, element_id=an_elem, direction="x")

        elif load.type == "point_moment":
            an_node = node_id_map[load.node_or_member_id]
            ss.moment_load(node_id=an_node, Tz=load.magnitude)

    return ss, node_id_map, elem_id_map


def solve(model: ModelDefinition) -> SolveResult:
    """
    Validate, build, and solve a structural model.

    Args:
        model: A complete ModelDefinition with nodes, members, supports, loads.

    Returns:
        SolveResult with status "ok" and populated results, or
        status "error" with a human-readable error message.
    """
    # Validate first
    error = validate_model(model)
    if error:
        return SolveResult(status="error", error=error)

    try:
        ss, node_id_map, elem_id_map = _build_system(model)
    except FEMException as e:
        return SolveResult(status="error", error=f"Model build error: {e.message}")
    except Exception as e:
        return SolveResult(status="error", error=f"Failed to build model: {str(e)}")

    # Solve
    try:
        ss.solve(verbosity=1)
    except FEMException as e:
        return SolveResult(status="error", error=f"Analysis failed: {e.message}")
    except AssertionError as e:
        msg = str(e)
        if "forces" in msg.lower():
            return SolveResult(
                status="error",
                error="No loads are applied to the structure.",
            )
        return SolveResult(
            status="error",
            error=f"Analysis failed: the structure may be unstable or ill-conditioned. ({msg})",
        )
    except np.linalg.LinAlgError:
        return SolveResult(
            status="error",
            error=(
                "The stiffness matrix is singular — the structure is a mechanism "
                "or has insufficient supports. Check that all degrees of freedom "
                "are properly restrained."
            ),
        )
    except Exception as e:
        return SolveResult(status="error", error=f"Unexpected solver error: {str(e)}")

    # Post-solve sanity check: detect numerically unstable solutions
    try:
        for an_nid in node_id_map.values():
            disp = ss.get_node_displacements(node_id=an_nid)
            if abs(disp["ux"]) > MAX_DISPLACEMENT_M or abs(disp["uy"]) > MAX_DISPLACEMENT_M:
                return SolveResult(
                    status="error",
                    error=(
                        "The structure is unstable — displacements are unreasonably large. "
                        "This usually means the structure is a mechanism (e.g. collinear truss "
                        "members, or insufficient supports for the applied loads)."
                    ),
                )
    except Exception:
        pass  # If displacement check fails, proceed with result extraction

    # Extract results
    result = SolveResult(status="ok")

    # Reverse maps for looking up model IDs from anastruct IDs
    rev_node_map = {v: k for k, v in node_id_map.items()}
    rev_elem_map = {v: k for k, v in elem_id_map.items()}

    # --- Reactions ---
    for an_node_id, node in ss.reaction_forces.items():
        model_node_id = rev_node_map.get(an_node_id, an_node_id)
        result.reactions.append(ReactionResult(
            node_id=model_node_id,
            Rx_kN=round(node.Fx, 6),
            Ry_kN=round(node.Fy, 6),
            Mz_kNm=round(node.Tz, 6),
        ))

    # Sort reactions by node ID
    result.reactions.sort(key=lambda r: r.node_id)

    # Build hinge lookup for result extraction
    hinge_map = {h.member_id: h for h in model.hinges}

    # --- Member results ---
    for model_mid, an_eid in elem_id_map.items():
        el_res = ss.get_element_results(element_id=an_eid, verbose=True)
        el = ss.element_map[an_eid]

        # Determine max absolute values
        n_min = el_res.get("Nmin", 0)
        n_max_val = el_res.get("Nmax", 0)
        n_max = max(abs(n_min), abs(n_max_val))
        n_signed = n_min if abs(n_min) >= abs(n_max_val) else n_max_val
        v_max = max(abs(el_res.get("Qmin", 0)), abs(el_res.get("Qmax", 0)))
        m_max = max(abs(el_res.get("Mmin", 0)), abs(el_res.get("Mmax", 0)))

        # Max displacement along the element
        defl_array = el_res.get("wtot")
        if defl_array is not None and len(defl_array) > 0:
            max_disp_m = float(np.max(np.abs(defl_array)))
        else:
            max_disp_m = max(abs(el_res.get("wmin", 0)), abs(el_res.get("wmax", 0)))

        # Location of max moment and shear (distance from start node)
        length = el.l
        m_loc = 0.0
        v_loc = 0.0

        m_array = el_res.get("M")
        if m_array is not None and len(m_array) > 0:
            m_idx = int(np.argmax(np.abs(m_array)))
            m_loc = round(m_idx / (len(m_array) - 1) * length, 4) if len(m_array) > 1 else 0.0

        q_array = el_res.get("Q")
        if q_array is not None and len(q_array) > 0:
            v_idx = int(np.argmax(np.abs(q_array)))
            v_loc = round(v_idx / (len(q_array) - 1) * length, 4) if len(q_array) > 1 else 0.0

        result.member_results.append(MemberResult(
            member_id=model_mid,
            N_max_kN=round(n_max, 6),
            V_max_kN=round(v_max, 6),
            M_max_kNm=round(m_max, 6),
            max_displacement_mm=round(max_disp_m * M_TO_MM, 6),
            M_max_location_m=round(m_loc, 4),
            V_max_location_m=round(v_loc, 4),
            N_signed_kN=round(n_signed, 6),
        ))

    result.member_results.sort(key=lambda r: r.member_id)

    # --- Node displacements ---
    for model_nid, an_nid in node_id_map.items():
        disp = ss.get_node_displacements(node_id=an_nid)
        result.nodes_displaced.append(NodeDisplacement(
            node_id=model_nid,
            dx_mm=round(disp["ux"] * M_TO_MM, 6),
            dy_mm=round(disp["uy"] * M_TO_MM, 6),
            rz_mrad=round(disp["phi_z"] * 1000, 6),  # rad -> mrad
        ))

    result.nodes_displaced.sort(key=lambda r: r.node_id)

    # --- Equilibrium check ---
    # Sum applied loads (point forces only; UDL resultants need member lengths)
    total_fx = 0.0
    total_fy = 0.0
    nc = {n.id: (n.x, n.y) for n in model.nodes}
    for load in model.loads:
        if load.type == "point_force":
            if load.direction == "Fx":
                total_fx += load.magnitude
            elif load.direction == "Fy":
                total_fy += load.magnitude
        elif load.type == "UDL":
            mid = load.node_or_member_id
            member = next((m for m in model.members if m.id == mid), None)
            if member:
                x1, y1 = nc[member.start_node]
                x2, y2 = nc[member.end_node]
                length = ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** 0.5
                if load.direction == "Fy":
                    total_fy += load.magnitude * length
                elif load.direction == "Fx":
                    total_fx += load.magnitude * length

    sum_rx = sum(r.Rx_kN for r in result.reactions)
    sum_ry = sum(r.Ry_kN for r in result.reactions)
    residual_x = abs(sum_rx + total_fx)
    residual_y = abs(sum_ry + total_fy)
    max_load = max(abs(total_fx), abs(total_fy), 1.0)
    tol = 1e-2 * max_load

    if residual_x > tol or residual_y > tol:
        result.warnings.append(
            f"Equilibrium check failed: force residuals "
            f"(Fx={residual_x:.3f} kN, Fy={residual_y:.3f} kN) "
            f"exceed tolerance {tol:.3f} kN. Results may be unreliable."
        )

    return result


# ---------------------------------------------------------------------------
# Diagram data extraction (for Plotly plots)
# ---------------------------------------------------------------------------


def get_diagram_data(model: ModelDefinition) -> Optional[dict[str, Any]]:
    """
    Solve the model and return detailed arrays for plotting diagrams.

    Returns None if model is invalid. Otherwise returns dict with keys:
        "members": list of dicts per member, each containing:
            - member_id, x_coords, y_coords (undeformed)
            - dx, dy (displacement arrays)
            - M, Q, N arrays (bending moment, shear, axial)
        "nodes": list of dicts per node with id, x, y, dx_mm, dy_mm
    """
    error = validate_model(model)
    if error:
        return None

    try:
        ss, node_id_map, elem_id_map = _build_system(model)
        ss.solve(verbosity=1)
    except Exception:
        return None

    rev_elem_map = {v: k for k, v in elem_id_map.items()}

    diagram_data: dict[str, Any] = {"members": [], "nodes": []}

    # Build hinge lookup for diagram data
    hinge_map = {h.member_id: h for h in model.hinges}

    for an_eid, model_mid in rev_elem_map.items():
        el = ss.element_map[an_eid]
        el_res = ss.get_element_results(element_id=an_eid, verbose=True)

        n_points = len(el_res.get("N", [])) if el_res.get("N") is not None else 50

        # Undeformed coordinates along the element
        # Use el.vertex_1/vertex_2 (not el.node_1.vertex) for correct positions
        x1, y1 = el.vertex_1.x, el.vertex_1.y
        x2, y2 = el.vertex_2.x, el.vertex_2.y
        x_coords = np.linspace(x1, x2, n_points).tolist()
        y_coords = np.linspace(y1, y2, n_points).tolist()

        # Displacement arrays
        defl = el_res.get("wtot")
        ext = el_res.get("u")

        # Check if member has hinges at both ends (truss-like behavior)
        h = hinge_map.get(model_mid)
        is_truss = h is not None and h.start_release and h.end_release

        member_data = {
            "member_id": model_mid,
            "x_coords": x_coords,
            "y_coords": y_coords,
            "N": el_res.get("N", np.zeros(n_points)).tolist(),
            "Q": el_res.get("Q", np.zeros(n_points)).tolist(),
            "M": el_res.get("M", np.zeros(n_points)).tolist(),
            "deflection": defl.tolist() if defl is not None else [0.0] * n_points,
            "extension": ext.tolist() if ext is not None else [0.0] * n_points,
            "length": el.l,
            "angle": el.angle,
            "is_truss": is_truss,
        }
        diagram_data["members"].append(member_data)

    # Build node coordinate lookup from model definition
    node_coords = {n.id: (n.x, n.y) for n in model.nodes}

    for model_nid, an_nid in node_id_map.items():
        disp = ss.get_node_displacements(node_id=an_nid)
        nx, ny = node_coords[model_nid]
        diagram_data["nodes"].append({
            "node_id": model_nid,
            "x": nx,
            "y": ny,
            "dx_mm": disp["ux"] * M_TO_MM,
            "dy_mm": disp["uy"] * M_TO_MM,
        })

    return diagram_data


# ---------------------------------------------------------------------------
# YAML serialization
# ---------------------------------------------------------------------------


def model_to_yaml(model: ModelDefinition) -> str:
    """
    Serialize a ModelDefinition to a YAML string with header comments.

    Args:
        model: The model to serialize.

    Returns:
        YAML string ready to write to a .fem.yaml file.
    """
    data: dict[str, Any] = {
        "metadata": {
            "name": model.name or "Untitled",
            "structure_type": model.structure_type,
            "format_version": 2,
            "created": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "description": model.description or "",
            "mesh_size": model.mesh_size,
        },
        "materials": [
            {"id": mat.id, "name": mat.name, "E_GPa": mat.E_GPa}
            for mat in model.materials
        ],
        "cross_sections": [
            {
                "id": s.id,
                "name": s.name,
                "A_cm2": s.A_cm2,
                "Iz_cm4": s.Iz_cm4,
                "material_id": s.material_id,
            }
            for s in model.cross_sections
        ],
        "nodes": [
            {"id": n.id, "x": n.x, "y": n.y}
            for n in model.nodes
        ],
        "members": [
            {
                "id": m.id,
                "start_node": m.start_node,
                "end_node": m.end_node,
                "section_id": m.section_id,
            }
            for m in model.members
        ],
        "supports": [
            {
                "node_id": s.node_id,
                "type": s.type,
                "spring_stiffness": s.spring_stiffness,
            }
            for s in model.supports
        ],
        "loads": [
            {
                "id": l.id,
                "type": l.type,
                "node_or_member_id": l.node_or_member_id,
                "direction": l.direction,
                "magnitude": l.magnitude,
                "udl_start": l.udl_start,
                "udl_end": l.udl_end,
            }
            for l in model.loads
        ],
    }
    if model.hinges:
        data["hinges"] = [
            {
                "member_id": h.member_id,
                "start_release": h.start_release,
                "end_release": h.end_release,
            }
            for h in model.hinges
        ]

    yaml_str = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return YAML_HEADER + yaml_str


def _migrate_v1_to_v2(d: dict) -> dict:
    """
    Convert a legacy v1 format dict (members have E_GPa/A_cm2/Iz_cm4/element_type)
    to v2 format (separate materials, cross_sections, hinges).
    """
    members_raw = d.get("members", [])

    # Collect unique materials by E_GPa
    mat_by_e: dict[float, int] = {}
    materials: list[dict] = []
    for m in members_raw:
        e = float(m.get("E_GPa", 210.0))
        if e not in mat_by_e:
            mat_id = len(materials) + 1
            mat_by_e[e] = mat_id
            mat_name = m.get("material", "Custom")
            # Extract just the material name (before " / " if present)
            if " / " in mat_name:
                mat_name = mat_name.split(" / ")[0]
            materials.append({"id": mat_id, "name": mat_name, "E_GPa": e})

    # Collect unique cross-sections by (A_cm2, Iz_cm4, material_id)
    sec_key_map: dict[tuple, int] = {}
    cross_sections: list[dict] = []
    for m in members_raw:
        e = float(m.get("E_GPa", 210.0))
        a = float(m.get("A_cm2", 100.0))
        iz = float(m.get("Iz_cm4", 10000.0))
        mat_id = mat_by_e[e]
        key = (a, iz, mat_id)
        if key not in sec_key_map:
            sec_id = len(cross_sections) + 1
            sec_key_map[key] = sec_id
            mat_name = m.get("material", "Custom")
            sec_name = mat_name.split(" / ")[1] if " / " in mat_name else "Custom"
            cross_sections.append({
                "id": sec_id, "name": sec_name,
                "A_cm2": a, "Iz_cm4": iz, "material_id": mat_id,
            })

    # Convert members and collect hinges from truss element_type
    new_members: list[dict] = []
    hinges: list[dict] = []
    for m in members_raw:
        e = float(m.get("E_GPa", 210.0))
        a = float(m.get("A_cm2", 100.0))
        iz = float(m.get("Iz_cm4", 10000.0))
        mat_id = mat_by_e[e]
        sec_id = sec_key_map[(a, iz, mat_id)]
        new_members.append({
            "id": m["id"],
            "start_node": m["start_node"],
            "end_node": m["end_node"],
            "section_id": sec_id,
        })
        if m.get("element_type") == "truss":
            hinges.append({
                "member_id": m["id"],
                "start_release": True,
                "end_release": True,
            })

    d["materials"] = materials
    d["cross_sections"] = cross_sections
    d["members"] = new_members
    if hinges:
        d["hinges"] = hinges
    return d


def _is_v1_format(d: dict) -> bool:
    """Check if a dict uses the legacy v1 format."""
    meta = d.get("metadata", {})
    if meta.get("format_version", 1) >= 2:
        return False
    if "materials" in d:
        return False
    # Check if members have old-style fields
    members = d.get("members", [])
    if members and ("E_GPa" in members[0] or "element_type" in members[0]):
        return True
    return not d.get("materials")


def yaml_to_model(yaml_dict: dict) -> ModelDefinition:
    """
    Deserialize a YAML dict (parsed from .fem.yaml) into a ModelDefinition.
    Handles both v1 (legacy) and v2 (current) formats.
    """
    # Migrate v1 to v2 if needed
    if _is_v1_format(yaml_dict):
        yaml_dict = _migrate_v1_to_v2(yaml_dict)

    meta = yaml_dict.get("metadata", {})

    model = ModelDefinition(
        structure_type=meta.get("structure_type", "custom"),
        name=meta.get("name", ""),
        description=meta.get("description", ""),
        mesh_size=int(meta.get("mesh_size", 50)),
    )

    for mat in yaml_dict.get("materials", []):
        model.materials.append(MaterialDef(
            id=mat["id"],
            name=mat.get("name", "Custom"),
            E_GPa=float(mat.get("E_GPa", 210.0)),
        ))

    for s in yaml_dict.get("cross_sections", []):
        model.cross_sections.append(CrossSectionDef(
            id=s["id"],
            name=s.get("name", "Custom"),
            A_cm2=float(s.get("A_cm2", 100.0)),
            Iz_cm4=float(s.get("Iz_cm4", 10000.0)),
            material_id=int(s.get("material_id", 1)),
        ))

    for n in yaml_dict.get("nodes", []):
        model.nodes.append(NodeDef(
            id=n["id"],
            x=float(n["x"]),
            y=float(n["y"]),
        ))

    for m in yaml_dict.get("members", []):
        model.members.append(MemberDef(
            id=m["id"],
            start_node=m["start_node"],
            end_node=m["end_node"],
            section_id=int(m.get("section_id", 1)),
        ))

    for s in yaml_dict.get("supports", []):
        model.supports.append(SupportDef(
            node_id=s["node_id"],
            type=s.get("type", "pinned"),
            spring_stiffness=s.get("spring_stiffness"),
        ))

    for l in yaml_dict.get("loads", []):
        model.loads.append(LoadDef(
            id=l["id"],
            type=l["type"],
            node_or_member_id=l.get("node_or_member_id", l.get("member_id", l.get("node_id", 0))),
            direction=l.get("direction", "Fy"),
            magnitude=float(l.get("magnitude", 0)),
            udl_start=l.get("udl_start"),
            udl_end=l.get("udl_end"),
        ))

    for h in yaml_dict.get("hinges", []):
        model.hinges.append(HingeDef(
            member_id=h["member_id"],
            start_release=h.get("start_release", False),
            end_release=h.get("end_release", False),
        ))

    return model


# ---------------------------------------------------------------------------
# JSON serialization (for API)
# ---------------------------------------------------------------------------


def model_to_dict(model: ModelDefinition) -> dict:
    """Convert ModelDefinition to a plain dict suitable for JSON serialization."""
    d: dict[str, Any] = {
        "format_version": 2,
        "structure_type": model.structure_type,
        "mesh_size": model.mesh_size,
        "materials": [
            {"id": mat.id, "name": mat.name, "E_GPa": mat.E_GPa}
            for mat in model.materials
        ],
        "cross_sections": [
            {
                "id": s.id, "name": s.name,
                "A_cm2": s.A_cm2, "Iz_cm4": s.Iz_cm4,
                "material_id": s.material_id,
            }
            for s in model.cross_sections
        ],
        "nodes": [{"id": n.id, "x": n.x, "y": n.y} for n in model.nodes],
        "members": [
            {
                "id": m.id,
                "start_node": m.start_node,
                "end_node": m.end_node,
                "section_id": m.section_id,
            }
            for m in model.members
        ],
        "supports": [
            {
                "node_id": s.node_id,
                "type": s.type,
                "spring_stiffness": s.spring_stiffness,
            }
            for s in model.supports
        ],
        "loads": [
            {
                "id": l.id,
                "type": l.type,
                "node_or_member_id": l.node_or_member_id,
                "direction": l.direction,
                "magnitude": l.magnitude,
                "udl_start": l.udl_start,
                "udl_end": l.udl_end,
            }
            for l in model.loads
        ],
    }
    if model.hinges:
        d["hinges"] = [
            {
                "member_id": h.member_id,
                "start_release": h.start_release,
                "end_release": h.end_release,
            }
            for h in model.hinges
        ]
    return d


def dict_to_model(d: dict) -> ModelDefinition:
    """Convert a plain dict (from JSON) to a ModelDefinition. Handles v1 and v2 formats."""
    # Migrate v1 to v2 if needed
    if _is_v1_format(d):
        d = _migrate_v1_to_v2(d)

    model = ModelDefinition(
        structure_type=d.get("structure_type", "custom"),
        mesh_size=int(d.get("mesh_size", 50)),
    )

    for mat in d.get("materials", []):
        model.materials.append(MaterialDef(
            id=mat["id"],
            name=mat.get("name", "Custom"),
            E_GPa=float(mat.get("E_GPa", 210.0)),
        ))

    for s in d.get("cross_sections", []):
        model.cross_sections.append(CrossSectionDef(
            id=s["id"],
            name=s.get("name", "Custom"),
            A_cm2=float(s.get("A_cm2", 100.0)),
            Iz_cm4=float(s.get("Iz_cm4", 10000.0)),
            material_id=int(s.get("material_id", 1)),
        ))

    for n in d.get("nodes", []):
        model.nodes.append(NodeDef(id=n["id"], x=float(n["x"]), y=float(n["y"])))

    for m in d.get("members", []):
        model.members.append(MemberDef(
            id=m["id"],
            start_node=m["start_node"],
            end_node=m["end_node"],
            section_id=int(m.get("section_id", 1)),
        ))

    for s in d.get("supports", []):
        model.supports.append(SupportDef(
            node_id=s["node_id"],
            type=s.get("type", "pinned"),
            spring_stiffness=s.get("spring_stiffness"),
        ))

    for l in d.get("loads", []):
        model.loads.append(LoadDef(
            id=l["id"],
            type=l["type"],
            node_or_member_id=l.get("node_or_member_id", 0),
            direction=l.get("direction", "Fy"),
            magnitude=float(l.get("magnitude", 0)),
            udl_start=l.get("udl_start"),
            udl_end=l.get("udl_end"),
        ))

    for h in d.get("hinges", []):
        model.hinges.append(HingeDef(
            member_id=h["member_id"],
            start_release=h.get("start_release", False),
            end_release=h.get("end_release", False),
        ))

    return model


def result_to_dict(result: SolveResult) -> dict:
    """Convert SolveResult to a plain dict suitable for JSON serialization."""
    return {
        "status": result.status,
        "error": result.error,
        "warnings": result.warnings,
        "reactions": [
            {
                "node_id": r.node_id,
                "Rx_kN": r.Rx_kN,
                "Ry_kN": r.Ry_kN,
                "Mz_kNm": r.Mz_kNm,
            }
            for r in result.reactions
        ],
        "member_results": [
            {
                "member_id": mr.member_id,
                "N_max_kN": mr.N_max_kN,
                "N_signed_kN": mr.N_signed_kN,
                "V_max_kN": mr.V_max_kN,
                "M_max_kNm": mr.M_max_kNm,
                "max_displacement_mm": mr.max_displacement_mm,
                "M_max_location_m": mr.M_max_location_m,
                "V_max_location_m": mr.V_max_location_m,
            }
            for mr in result.member_results
        ],
        "nodes_displaced": [
            {
                "node_id": nd.node_id,
                "dx_mm": nd.dx_mm,
                "dy_mm": nd.dy_mm,
                "rz_mrad": nd.rz_mrad,
            }
            for nd in result.nodes_displaced
        ],
    }
